general {
    lock_cmd = pidof hyprlock || hyprlock 
    before_sleep_cmd = hyprlock -c $HOME/.config/swindle/hyprlock/hyprlock.conf
}

listener {
    timeout = 600                        
    on-timeout = hyprlock -c $HOME/.config/swindle/hyprlock/hyprlock.conf
}
